In [1]:
import dgl
import torch as th

Using backend: pytorch


In [2]:
# 边 0->1, 0->2, 0->3, 1->3
u, v = th.tensor([0, 0, 0, 1]), th.tensor([1, 2, 3, 3])

g = dgl.graph((u, v))

print(g)  # 图中节点的数量是 DGL 通过给定的图的边列表中最大的点 ID 推断所得出的

Graph(num_nodes=4, num_edges=4,
      ndata_schemes={}
      edata_schemes={})


In [3]:
print(g.nodes())  # 获取节点的ID

tensor([0, 1, 2, 3])


In [4]:
print(g.edges())  # 获取边的对应端点

(tensor([0, 0, 0, 1]), tensor([1, 2, 3, 3]))


In [5]:
print(g.edges(form='all'))  # 获取边的对应端点和边ID

(tensor([0, 0, 0, 1]), tensor([1, 2, 3, 3]), tensor([0, 1, 2, 3]))


In [6]:
# 如果具有最大 ID 的节点没有边，在创建图的时候，用户需要明确地指明节点的数量。
g = dgl.graph((u, v), num_nodes=8)
g.nodes(), g.edges(form='all')

(tensor([0, 1, 2, 3, 4, 5, 6, 7]),
 (tensor([0, 0, 0, 1]), tensor([1, 2, 3, 3]), tensor([0, 1, 2, 3])))

In [7]:
edges = th.tensor([2, 5, 3]), th.tensor([3, 5, 0])  # 边：2->3, 5->5, 3->0
g64 = dgl.graph(edges)  # DGL默认使用int64
print(g64.idtype)

torch.int64


In [8]:
g32 = dgl.graph(edges, idtype=th.int32)  # 使用int32构建图
g32.idtype

torch.int32

In [9]:
g64_2 = g32.long()  # 转换成int64
g64_2.idtype

torch.int64

In [10]:
g32_2 = g64.int()  # 转换成int32
g32_2.idtype

torch.int32